### PR TITLE
Improvements to docs

### PR DESCRIPTION
**Pull request by zoe-vb**
Completed docs on single user mode and also added binaries.

### CODE REVIEW

**Comment by devos50** [comment]
Thanks! Are we sure that we want to include these binaries (5000+ files) directly in the repo?

**Comment by zoe-vb** [comment]
For permanency the most viable option is to store them here or on the internet archive.  As a lot of projects end up just disappearing into the depths of the internet from link rot. I suggest that I upload them to the internet archive, however if I compress the binaries into one archive I reckon that they could be hosted here for now as none of them are actually apple binaries and are all from Saurik's AppTapp repo.

**Comment by zoe-vb** [comment]
Okay tidied up some more and compressed binaries, I reckon its ready for a PR

**Comment by devos50** [comment]
Thanks!

**Pull request merged**
